# Uncomment the next line to define a global platform for your project/Users/chdo/Documents/GitHub/HttpServerDebug
 platform :ios, '9.3'

inhibit_all_warnings!

target 'iOS_Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS_Example
  pod 'Croissant' , :path => '../'
  pod 'AFNetworking'
  
  target 'iOS_ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOS_ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'DD_LEGACY_MACROS=1']
    end
  end
end
