# Uncomment the next line to define a global platform for your project/Users/chdo/Documents/GitHub/HttpServerDebug
 platform :ios, '9.0'

inhibit_all_warnings!

target 'iOS_Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS_Example
  pod 'CDCroissant' , :path => '../'
  pod 'AFNetworking'
  
  target 'iOS_ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOS_ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
