# Uncomment the next line to define a global platform for your project
 platform :ios, '9.3'

inhibit_all_warnings!

target 'iOS_Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS_Example
  pod 'Croissant' , :path => '../'
  
  target 'iOS_ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOS_ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
